# Generated by Django 2.0.7 on 2018-09-02 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_auto_20180902_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(unique=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
