# Generated by Django 2.0.7 on 2018-08-02 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_photo_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='owner',
        ),
    ]
