# Generated by Django 2.0.7 on 2018-09-02 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0003_auto_20180902_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
