# Generated by Django 2.0.7 on 2018-08-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='model_file',
            name='settings',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='model_file',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
