# Generated by Django 2.0.7 on 2018-08-09 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_auto_20180808_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='file',
            field=models.FileField(unique=True, upload_to='media/'),
        ),
    ]
