# Generated by Django 2.0.7 on 2018-08-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_auto_20180809_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model_file',
            name='file',
            field=models.FileField(upload_to='media/'),
        ),
    ]
